### ISSUE TITLE
Come up with a project name.

### ISSUE THREAD

**Issue by JoeBiller** [JoeBiller/Group_6#12]
We need a catchy name for the project.

Once we all agree on one, we need to:

- Revise the `README.md` to introduce the project under its new name.
- Revise the `SRS.md` to include the new name.
- Replace all instances of *[Project Name]* in the `User Stories` Wiki page with the new name.

We will discuss this issue in our next meeting.

**Comment by Mak0918** [comment]
Ok gotcha.

Thank you,

Makayla McClain
________________________________
From: Matthew Lane ***@***.***>
Sent: Wednesday, September 7, 2022 9:56:44 PM
To: JoeBiller/Group_6 ***@***.***>
Cc: McClain, Makayla ***@***.***>; Assign ***@***.***>
Subject: [JoeBiller/Group_6] Come up with a project name. (Issue #12)


We need a catchy name for the project.

Once we all agree on one, we need to:

  *   Revise the README.md to introduce the project under its new name.
  *   Revise the SRS.md to include the new name.
  *   Replace all instances of [Project Name] in the User Stories Wiki page with the new name.

We will discuss this issue in our next meeting.

**Comment by JoeBiller** [comment]
It has been determined! The project will be called "amid".
